#!/bin/bash

# This command will start the node.js wifi connection manager that sets up
# the Access Point and only exits when a connection is made.
npm start

# We run the Python app after the wifi connection has been established
# and the previous command has exited.
cd /app && python main.py

# If our Python server ever crashed/exited, the following loop will
# allow us to still access our device on the web terminal.
while true
do
	echo "App exited but container is still running to allow web terminal access"
	sleep 3600
done
